LB-381: MessyBrainz: create clusters using fetched artist MBIDs.
metabrainz/messybrainz-server pull request #47
Opened 2018-07-08 14:12 UTC by kartikeyaSh

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
We have script to fetch artist MBIDs from MusicBrainz database now we need to create clusters using
those artist MBIDs.

* JIRA ticket (_optional_): [LB-381](https://tickets.metabrainz.org/browse/LB-381)

# Action
Added functionality to create clusters using fetched artist MBIDs.
recording_artist_join table is joined with recording_json on equal recording MBID.
And a little modification on how entity MBIDs and gids are fetched is created in four new functions.
After that passed those functions to clustering functions in db_common.py to create clusters.

2018-07-18 14:14 UTC, mayhem reviewed
I can't see anything wrong with it, but it is also very hard to see what this does. I'm really having a hard time with this. :( I think I need to actually run the code and carefully paw through the results to see where we are at. I'll do my best to do that tomorrow.

2018-08-05 05:17 UTC, paramsingh commented on manage.py
> +    print("Creating artist_credit clusters...")
using `print` and `logging` is a bit inconsistent, is there a reason why we're using both? can we try to only use `logging`?

2018-08-05 05:17 UTC, paramsingh commented on admin/sql/updates/2018-07-05-alter-recording-artist-join.sql
> +ALTER TABLE recording_artist_join ADD COLUMN artist_mbids_array UUID[] NOT NULL;
would naming this just `artist_mbids` be better? we don't need the type in column name.

2018-08-05 05:17 UTC, paramsingh commented on messybrainz/db/artist.py
> +        get_recordings_metadata_using_artist_mbids,
the docstring for this function in `db.common` is out of date, I guess. It doesn't mention the `get_metadata` function.(https://github.com/metabrainz/messybrainz-server/blob/master/messybrainz/db/common.py)

2018-08-10 15:21 UTC, kartikeyaSh commented on manage.py
> +    print("Creating artist_credit clusters...")
I use logging.INFO for some verbose and logging.DEBUG for a lot of verbose. Above it we have logging.WARNING which I don't think is appropriate to use for displaying the information in print. So, I opted for print instead of logging.

2018-09-10 12:15 UTC, mayhem requested changes
So close!

2018-09-10 12:15 UTC, mayhem commented on manage.py
> +            logging.basicConfig(format='%(message)s', level=logging.DEBUG)
What happens when the user passes "DOOFUS" from the command line? You should check to make sure that passed values are always legal. If no valid ones are passed, you might give a warning that it was ignored and carry on using the default logging value.

2018-10-30 12:21 UTC, mayhem commented
OK, finally time to merge this! Venga!

2018-10-30 12:21 UTC, mayhem approved these changes
👍

2018-10-30 12:21 UTC, merged