LB-387: MessyBrainz: Add API endpoints to fetch MSIDs or MBIDs.
metabrainz/messybrainz-server pull request #51
Opened 2018-08-05 15:45 UTC by kartikeyaSh

# Summary
Add API endpoints to get all MBIDs and MSIDs using a given MSID
and another endpoint to get all the MSIDs using a given MBID.

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
We have created clusters now we need API endpoints to make use of the clustered data.

* JIRA ticket (_optional_): [LB-387](https://tickets.metabrainz.org/browse/LB-387)

# Solution

Added two API endpoints one to access information using MSIDs. And another one to access information using MBIDs.

2018-09-30 10:49 UTC, mayhem requested changes
I've left some comments that need to be addressed, but we really need to discuss the API structure for MSB before we continue working on this PR.

2018-09-30 10:49 UTC, mayhem commented on messybrainz/db/recording.py
> +def get_gids_using_cluster_id(connection, cluster_id):
Change to get_recording_msids_from_cluster_id ?

2018-09-30 10:49 UTC, mayhem commented on messybrainz/db/recording.py
> +def get_mbids_using_cluster_id(connection, cluster_id):
s/using/from/ ?

2018-09-30 10:49 UTC, mayhem commented on messybrainz/db/release.py
> +def get_msids_using_cluster_id(connection, cluster_id):
get_release_msids_from_cluster_id ?

2018-09-30 10:49 UTC, mayhem commented on messybrainz/webserver/views/api.py
>  api_bp = Blueprint('api', __name__)
We should use /ws/1 as the prefix for the API.

2018-09-30 10:49 UTC, mayhem commented on messybrainz/webserver/views/api.py
> +
There are likely other exceptions the DB is going to throw -- we should catch more exceptions here.

2018-09-30 10:49 UTC, mayhem commented on messybrainz/webserver/views/api.py
> +    includes = request.args.getlist('includes')
At the summit we agreed to no longer use includes, but resource selectors. Take a look at this document:

https://docs.google.com/document/d/1ClnGKq3rsagERpoAjCjf3Jl1DoCfolzlgj0OXmAy9Pg/edit?usp=sharing

But, I don't see includes being used -- for now just remove them please.

2020-05-01 16:31 UTC, paramsingh commented
Closing this as the repository has been merged into [listenbrainz-server](https://github.com/metabrainz/listenbrainz-server).

2020-05-01 16:31 UTC, closed without merging